version: "3.9"

services:
  app:
    build: .
    container_name: nairobi-gems-backend
    env_file: .env
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000
